language: python
python:
- '3.6'
- '3.7'
dist: xenial
install:
- pip install pipenv
- pipenv install --dev
script:
# - pylint **/*.py
- python -m pytest --cov=darkseed
- ./docs.py
after_success:
- codecov
deploy:
- provider: pages
  skip_cleanup: true
  local-dir: "./docs/html"
  github_token:
    secure: "oCmbJgvlqIHskmsjWv36aqdw+oBjoTUJu1B9AhF7rePqHkA2R1DgrWcTmCWDc80CHfOMOUGP7bT3iqk157mLqjCezH/PNCbibt8As1pfYxyj94UzOqIwjRUiGJoj1nWFLjnh3RMcQoteiTCeDn+6DAYQm3uwexzcpWWUsy3PLr/bS7C9rQcOX6/YfaCEvkvPgvehjtHyNd+aEOIt2khygd35f2qZa92E9DopW0HGQ5KYYdyho8XvFnbMinHrso7O/cHs/+yP+IAuExBjlE5Ds+QVj0pzHrEEwoYbOs3GuAPzOQgdbGcCCwwY2y5D1BA1LI/1Bwgfq50zqRdu8OH+1OzgXRQiBbhTxm+JytHhm3jMKIpeOBnzCv7lDfVSSWUE+TvSnHwsOyEDgHxW1S/A96g2l6oxF6stBptWmJQZ3xBbBDfXg1ohyBABw34cxsyLuzLZYDWH7CjuBrVhGSxVYC66RdZbhDqqELecqnBFymKrCYuOlJXciKx+hzslLyhzOcQ7Dt4vY8NtEQy3asfvSF1f4zppnEhRZqE8eLyjJG3zsw6xed/B817/TdmQsSrobM824YTlKddsCBX7raCcttVG5B2h+c/QfHAi0YdGy5BWQrloiV0XoLL7r2rzVS7QADoU0KadN0A9rHJQmUejS98E0NNyoU7anqLQHWrksaQ="
  on:
    branch: master
    tags: true
- provider: pypi
  user: digitalvapor
  skip_cleanup: true
  password:
    secure: "QVMBMKW/NvirCkSdBBi3/p9LA15GBqkfKVSW+OaOf1BhlQCs3PMORZonZ2RjZnSAbGrx8aSQDi6xazyRgat1PSG7WiWW82InlcSadoHzeH9GiI8wqcMh08CCpdKIgfE6waFSVLPYGXDQVTiKw2zRvJi2SVBnuZcmbCy6ddKh1++nEWKt0O6pkcB1YLG4VbbNokjWbH8qGbVlnIPSeMqQtr4sTQkDXXPuPTUTREtVJUvqSR64fyj0zyYcUTh8OXxdPuDBmHLfkpjMEPMg2ny8929MqYelJu5+VZNPanKbeDqBNO2iiyF/XpU1jRFSYqZIa5wa29h0+6ZoiK0L7wxNlyz25GkA3MdYc6ybAS/GUfQzIjtv1c0nrS+you/t8eJ5D4CCBRssoog4CM0tZWW+NKV2gslwQOogAQw99OXCkaAvZIdlgBoo9cliPYLYyv4ZqzFtk6witGb2j39GbQzUXIjpwBAS0qa1bVFkrnRn7zAbuX9GDxERhpcnLIlt9P2BTNoFScA8iWhMQ9RcX68XETx7BGzSKwflCL9FYxaI8EdvbfTQWhp8sgoTxkt7sDRU5dd3P8MEQtwnyM/e+VAYlaBDy3WQuML6dKGfy3HlnkLbLXgZDUkPePED8NmoUzppM3FBkORaKiO+pks9OI2VGBnDRzgdgDEN+ohgGAPSBl4="
  on:
    tags: true
